version: "3"

services:
  postgres:
    image: postgres
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
  cache:
    image: redis
    ports:
      - "6379:6379"
#  primeapi:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=postgres
#      - REDIS_HOST=cache
#      - REDIS_PORT=6379